// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sepnkuvrmdcxjbxpyime.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlcG5rdXZybWRjeGpieHB5aW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3NDQwNjMsImV4cCI6MjA0OTMyMDA2M30.1dhDbRHZh-9SzqDdzZ73dzYyieWgzjHauqIR7Y9aBVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);